import { describe, it, expect, beforeEach } from 'vitest'
import { render, screen } from '@testing-library/react'
import HistoryPage from './HistoryPage'

function seedHistory(entries) {
  localStorage.setItem('triageHistory', JSON.stringify(entries))
}

describe('HistoryPage fallback badge', () => {
  beforeEach(() => {
    localStorage.clear()
  })

  it('shows a Fallback badge for entries generated by the mock fallback', () => {
    seedHistory([
      {
        message: 'Server down now',
        category: 'Technical Problem',
        urgency: 'High',
        recommendedAction: 'Suggest user to restart their browser.',
        reasoning: 'Keyword-based guess.',
        source: 'mock',
        timestamp: new Date().toISOString(),
      },
    ])

    render(<HistoryPage />)

    expect(screen.getByText('⚠ Fallback')).toBeInTheDocument()
  })

  it('does not show a Fallback badge for real AI-sourced entries', () => {
    seedHistory([
      {
        message: 'Why was I charged twice?',
        category: 'Billing Issue',
        urgency: 'Medium',
        recommendedAction: 'Ask user to check billing portal.',
        reasoning: 'Real AI reasoning.',
        source: 'ai',
        timestamp: new Date().toISOString(),
      },
    ])

    render(<HistoryPage />)

    expect(screen.queryByText('⚠ Fallback')).not.toBeInTheDocument()
  })

  it('sorts entries newest-first by timestamp, not alphabetically by message', () => {
    seedHistory([
      {
        message: 'Zebra was the first message sent, an hour ago',
        category: 'General Inquiry',
        urgency: 'Low',
        recommendedAction: 'Respond with FAQ link.',
        reasoning: 'Reasoning A.',
        timestamp: new Date(Date.now() - 60 * 60 * 1000).toISOString(),
      },
      {
        message: 'Apple was the second message sent, just now',
        category: 'General Inquiry',
        urgency: 'Low',
        recommendedAction: 'Respond with FAQ link.',
        reasoning: 'Reasoning B.',
        timestamp: new Date().toISOString(),
      },
    ])

    render(<HistoryPage />)

    const messages = screen.getAllByText(/was the (first|second) message sent/)
    expect(messages[0]).toHaveTextContent('Apple was the second message sent, just now')
    expect(messages[1]).toHaveTextContent('Zebra was the first message sent, an hour ago')
  })

  it('does not crash on legacy entries with no source field', () => {
    seedHistory([
      {
        message: 'Old entry before this field existed',
        category: 'General Inquiry',
        urgency: 'Low',
        recommendedAction: 'Respond with FAQ link.',
        reasoning: 'Legacy reasoning.',
        timestamp: new Date().toISOString(),
      },
    ])

    render(<HistoryPage />)

    expect(screen.getByText(/Old entry before this field existed/)).toBeInTheDocument()
    expect(screen.queryByText('⚠ Fallback')).not.toBeInTheDocument()
  })
})
